export const leagues = {
    1: 'Lliga Polar',
    2: 'Minilliga',
    3: 'Lliga Floral',
    4: 'Lliga del Drac',
    5: 'Lliga del Raig',
    6: 'Lliga del Meló',
    7: 'Lliga Seca',
    8: 'Lliga Major',
    9: 'Lliga de Catalunya',
    10: 'Lliga Castanyera',
    11: 'Lliga de la Mosca',
    12: 'Lliga de Nadal',
}
export const leagues_emoji = {
    1: '⛄️',
    2: '🐥',
    3: '🌻',
    4: '🐉',
    5: '⚡',
    6: '🍈',
    7: '💨',
    8: '💃🏻',
    9: '💛',
    10: '🌰',
    11: '🪰',
    12: '🐫🐫🐫',
}
